
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anonymous
 */
public class DoctorInformation extends javax.swing.JFrame {

    /**
     * Creates new form DoctorInformation
     */
    DatabaseHandler databaseHandler = new DatabaseHandler();
    public DoctorInformation() {
        initComponents();
    }
    public DoctorInformation(DatabaseHandler ob){
        initComponents();
        databaseHandler = ob;
        ResultSet rs = databaseHandler.fetchTableData("doctor");
        doctorTable.setModel(DbUtils.resultSetToTableModel(rs));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        doctorTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        doctorIdTXT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        doctorNameTXT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        doctorSpeTXT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        doctorDeptTXT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        doctorTypeTXT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        doctorChargeTXT = new javax.swing.JTextField();
        addNewRec = new javax.swing.JButton();
        updateRec = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        doctorWHourTXT = new javax.swing.JTextField();
        backBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doctorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        doctorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(doctorTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 84, 790, 454));

        jLabel1.setText("Doctor ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 87, -1, -1));
        getContentPane().add(doctorIdTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 84, 191, -1));

        jLabel2.setText("Doctor Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 139, -1, -1));
        getContentPane().add(doctorNameTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 136, 191, -1));

        jLabel3.setText("Specialist:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 189, -1, -1));
        getContentPane().add(doctorSpeTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 186, 193, -1));

        jLabel4.setText("Department:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 253, -1, -1));
        getContentPane().add(doctorDeptTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 250, 191, -1));

        jLabel5.setText("Type:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 306, -1, -1));
        getContentPane().add(doctorTypeTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 303, 191, -1));

        jLabel6.setText("Charge:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 366, -1, -1));

        doctorChargeTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorChargeTXTActionPerformed(evt);
            }
        });
        getContentPane().add(doctorChargeTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 363, 191, -1));

        addNewRec.setText("Add New Record");
        addNewRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewRecActionPerformed(evt);
            }
        });
        getContentPane().add(addNewRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 474, -1, -1));

        updateRec.setText("Update Record");
        updateRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRecActionPerformed(evt);
            }
        });
        getContentPane().add(updateRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 474, -1, -1));

        refresh.setText("Refresh Record");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, -1, -1));

        jLabel7.setText("Information Table of Doctors");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, -1, -1));

        jLabel8.setText("Working Hour:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 415, -1, -1));
        getContentPane().add(doctorWHourTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 412, 191, -1));

        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });
        getContentPane().add(backBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doctorChargeTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorChargeTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorChargeTXTActionPerformed

    private void doctorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorTableMouseClicked
        // TODO add your handling code here:
        int i = doctorTable.getSelectedRow();
        TableModel tbModel = doctorTable.getModel();
        doctorIdTXT.setText(tbModel.getValueAt(i, 0).toString());
        doctorNameTXT.setText(tbModel.getValueAt(i, 1).toString());
        doctorSpeTXT.setText(tbModel.getValueAt(i, 2).toString());
        doctorDeptTXT.setText(tbModel.getValueAt(i, 3).toString());
        doctorTypeTXT.setText(tbModel.getValueAt(i, 4).toString());
        doctorChargeTXT.setText(tbModel.getValueAt(i, 5).toString());
        doctorWHourTXT.setText(tbModel.getValueAt(i, 6).toString());
    }//GEN-LAST:event_doctorTableMouseClicked

    private void addNewRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewRecActionPerformed
        // TODO add your handling code here:
        String id = doctorIdTXT.getText().toString();
        String name = doctorNameTXT.getText().toString();
        String spe = doctorSpeTXT.getText().toString();
        String dep = doctorDeptTXT.getText().toString();
        String type = doctorTypeTXT.getText().toString();
        String chrg = doctorChargeTXT.getText().toString();
        String wh = doctorWHourTXT.getText().toString();
        if(id.isEmpty() || name.isEmpty()||spe.isEmpty()||dep.isEmpty()||type.isEmpty()||chrg.isEmpty()||wh.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Fill all the field");
        }
        else if(databaseHandler.insertDataIntoDoctor(id, name, spe, dep, type, chrg, wh))
        {
            JOptionPane.showMessageDialog(null,"New Record Inserted");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Data Already Inserted For This ID");
        }
    }//GEN-LAST:event_addNewRecActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        ResultSet rs = databaseHandler.fetchTableData("doctor");
        doctorTable.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_refreshActionPerformed

    private void updateRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRecActionPerformed
        // TODO add your handling code here:
        String id = doctorIdTXT.getText().toString();
        String name = doctorNameTXT.getText().toString();
        String spe = doctorSpeTXT.getText().toString();
        String dep = doctorDeptTXT.getText().toString();
        String type = doctorTypeTXT.getText().toString();
        String chrg = doctorChargeTXT.getText().toString();
        String wh = doctorWHourTXT.getText().toString();
        if(databaseHandler.updateDataIntoDoctor(id, name, spe, dep, type, chrg, wh))
        {
            JOptionPane.showMessageDialog(null,"Update Successfully");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Failed Update");
        }
    }//GEN-LAST:event_updateRecActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainDashboard(databaseHandler).setVisible(true);
    }//GEN-LAST:event_backBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewRec;
    private javax.swing.JButton backBTN;
    private javax.swing.JTextField doctorChargeTXT;
    private javax.swing.JTextField doctorDeptTXT;
    private javax.swing.JTextField doctorIdTXT;
    private javax.swing.JTextField doctorNameTXT;
    private javax.swing.JTextField doctorSpeTXT;
    private javax.swing.JTable doctorTable;
    private javax.swing.JTextField doctorTypeTXT;
    private javax.swing.JTextField doctorWHourTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refresh;
    private javax.swing.JButton updateRec;
    // End of variables declaration//GEN-END:variables
}
